HAI 1.2
        I HAS A VAR
	I HAS A NUM ITZ 2		BTW NUM = 2
	I HAS A FLOT ITZ 2.5	        BTW FLOT = 2.5
	I HAS A ANS ITZ SUM OF 7 AN 6	BTW ANS = 13
	I HAS A NAME ITZ "erika"	BTW NAME = "erika"

BTW printing values
	VISIBLE "NUM = " NUM
	VISIBLE "FLOT = " FLOT
	VISIBLE "ANS = " ANS
	VISIBLE "NAME = " NAME

BTW assignment statement:
	NUM R 17
	FLOT R DIFF OF 2.5 AN 1.3
	
	VISIBLE "NUM is now " NUM
	VISIBLE "FLOT is now " FLOT

KTHXBYE
